### ISSUE TITLE
paper-icon-button accessibility issues: Windows specific

### ISSUE THREAD

**Issue by lpalmaro** [PolymerElements/paper-icon-button#10]
Note: Please note that the first rounds of accessibility testing / issue reporting were done using Chrome on Mac with VoiceOver enabled, as well as Chrome on Chrome OS with ChromeVox enabled. This next round was done on the Windows platform, on both Chrome and Firefox with the NVDA screen reader enabled. Once the team addresses the issues across platforms and screen readers, we will also do a final test using Windows and the JAWS screen reader, a heavily used combo that certainly needs to work smoothly. 

Issues: 

Chrome / NVDA: 
When navigating linearly and I reach the row of buttons, NVDA reads all the buttons in the row at once, as opposed to being able to use the arrow key to navigate to each individually. 

Firefox /  NVDA: 
When navigating through the buttons, the only spoken feedback I receive is ""clickable", with no other context. I also hear two ""blank"" instances in between the first row of buttons and the heading ""styled"
"

**Comment by notwaldorf** [comment]
The `blank` instances are expected, since I think there used to be `<br>`s in between each button.

**Comment by lpalmaro** [comment]
Yes, the blanks are fine in this instance.

On Mon, Jun 1, 2015 at 11:11 AM, Monica Dinculescu <notifications@github.com

**Comment by notwaldorf** [comment]
This is no longer an issue.
