### ISSUE TITLE
paper-icon-button-light ignores `noink`

### ISSUE THREAD

**Issue by bicknellr** [PolymerElements/paper-icon-button#100]
### Description

paper-icon-button-light ignores `noink`.
### Expected outcome

With `noink` set, the button should not ripple when clicked.
### Actual outcome

The button always ripples when clicked.
### Live Demo

http://jsbin.com/cobefek/edit?html,output
### Browsers Affected

All

**Comment by danbeam** [comment]
fixed by https://github.com/PolymerElements/paper-icon-button/pull/111 btw
