### ISSUE TITLE
`hidden` attribute not working on Chrome

### ISSUE THREAD

**Issue by andrewspy** [PolymerElements/paper-icon-button#103]
### Description
`hidden` attribute not working on Chrome. Tested working on Firefox/Edge.

### Expected outcome

Should be hidden

### Actual outcome

Not hidden

### Live Demo

```html
<paper-icon-button icon="search" on-tap="searchAction" hidden></paper-icon-button>
```

### Steps to reproduce

1. Put a `paper-icon-button` element in the page with `hidden` attribute.
2. Open the page in a web browser.

### Browsers Affected

- [x] Chrome (Version 53.0.2785.116 m (64-bit))
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by andrewspy** [comment]
It is working now when I unit test it. Probably need to investigate on my app. closing it now. Sorry for the trouble.

**Comment by andrewspy** [comment]
Just wanted to add that you need to specify a CSS style inside a custom element to properly hide `<paper-icon-button>` inside the custom element, i.e:-

```html
<style>
paper-icon-button[hidden] {
    display: none;
}
</style>
```

Took me a while to figure that out. Thanks anyway!

**Comment by CSchmitz81** [comment]
Thanks for the tip, although this still sounds like a bug to me.  Shouldn't it be possible to do this in the paper-icon-button code so we don't have to keep putting this boiler plate code into the CSS?  Is there some reason it's not possible to be built into the component?

**Comment by CSchmitz81** [comment]
It looks like the style of the component can be updated in the same way to support this.  This probably just wasn't done for paper-icon-button, so I'd definitely consider this a bug still.

**Comment by Lange** [comment]
Bumping this -- is there a good reason why this element does not define its own `[hidden]` style when so many official Paper elements others do?
