### ISSUE TITLE
ink not being removed on Safari

### ISSUE THREAD

**Issue by doughaase** [PolymerElements/paper-icon-button#114]
### Description
When tapping a paper-icon-button, the ink is not being removed on Safari.

### Expected outcome

The ink should be removed when the user releases the button.

### Actual outcome

The button stays colored, like it's still being pressed/selected.

[Screenshot](http://i.imgur.com/zFpVrsZ.png)

### Browsers Affected

- [ x ] Safari 10 (only version of Safari that I tested)
It's working fine on Chrome and Firefox, both desktop and mobile versions.

**Comment by doughaase** [comment]
Works ok with paper-button and the iron-icon inside it, though. So I switched to it.

**Comment by notwaldorf** [comment]
Do you have repro steps? It sounds like something else is missing, since the demo doesn't seem to be doing this. Closing, but please reopen with repro steps
