### ISSUE TITLE
paper-icon-button-light gone in 2.0

### ISSUE THREAD

**Issue by rictic** [PolymerElements/paper-icon-button#118]
It looks like https://github.com/PolymerElements/paper-icon-button/commit/912413ef896f2c39939f6410ef1a2038f031ad01 deleted the demo of paper-icon-button-light, and then https://github.com/PolymerElements/paper-icon-button/commit/4f600c7c4f5296063a58d00b26aae18fbbee374a deleted the element itself.

Was this intended? If so, I guess users should move to paper-icon-button?

**Comment by notwaldorf** [comment]
`Paper-icon-button-light` was a type extension of a native `button`, which does not work with Polymer 2 :(
I guess yes, move to regular `paper-icon-button`?

**Comment by notwaldorf** [comment]
Just merged a PR noting that
