### ISSUE TITLE
Firefox Quantum error:  TypeError: this._meta.byKey is not a function error 

### ISSUE THREAD

**Issue by Mikebarson** [PolymerElements/paper-icon-button#125]
### Description
I'm getting error:

``` TypeError: this._meta.byKey is not a function```

### Expected outcome

No errors

### Actual outcome

Page does not render properly
![screen shot 2017-11-15 at 9 23 08 pm](https://user-images.githubusercontent.com/13252897/32877987-088dccf0-cadf-11e7-9adc-eb753f14f16a.png)

### Steps to reproduce

1. Import paper-icon-button element under app-drawer-layout
2. Open the page in Firefox (Quantum) web browser.
3. Open console

### Browsers Affected

- [ /] Firefox Quantum

**Comment by notwaldorf** [comment]
Can you provide a JSBin with repro steps? This for example works fine: http://jsbin.com/yafodup/1/edit?html,output

**Comment by Mikebarson** [comment]
Here's the jsbin. http://jsbin.com/velovef/edit?html,console,output 
I'm not sure why but in jsbin it's not showing the error ``` this._meta.byKey is not a function ``` but instead 

```
"error"
"Script error. (line 0)"
```

**Comment by justinmandac** [comment]
Hi! I encountered the same issue earlier. @Mikebarson do you have the LastPass extension installed? Disabling it might do the trick.
It was found in [this related issue](https://github.com/home-assistant/home-assistant-polymer/issues/428) that LastPass was the culprit.

**Comment by Mikebarson** [comment]
Thanks! That fixed it for me.
