### ISSUE TITLE
Icon not showing up with Polymer 2.0

### ISSUE THREAD

**Issue by auguster** [PolymerElements/paper-icon-button#129]
### Description
Using an iron-icon from iron-icons with paper-icon-button using the `icon` attribute.

### Expected outcome
The icon should be displayed.

### Actual outcome
The icon doesn't show up. When using a custom icon with `src` attribute, it works.

### Workaround
Import iron-icons directly in the paper-icon-button fix the issue.

**Comment by adzadzadz** [comment]
same issue, although I tried the workaround with v2.2.0, it's not working for me..

**Comment by adzadzadz** [comment]
Actually, it was working fine for me it's just that the background color #fff is the same as my paper-icon-button color.. Silly me haha

**Comment by notwaldorf** [comment]
i can't repro this: http://jsbin.com/javaxim/edit?html,output
The documentation already says you _must_ include an icon set (like `iron-icons/iron-icons.html`), and  no default one is provided, so i think this is working as intended.

please re-open this if you have repro steps.

**Comment by auguster** [comment]
I confirm that it was a problem on our end. We had a mixed up in the versions between Polymer 1 and 2 because of a `.bower.json` (hidden) in our project.

Sorry for the issue, I'll try to make reproductible example next time, thanks for the link, I didn't know about Polygit ;-)

**Comment by notwaldorf** [comment]
No worries! Glad you sorted it out :)
