### ISSUE TITLE
Icon size doesn't reflect the one set in `--paper-icon-button`

### ISSUE THREAD

**Issue by agektmr** [PolymerElements/paper-icon-button#22]
If I give `paper-icon-button` a different size than default one by using `--paper-icon-button`, for example

```css
    paper-icon-button {
      --paper-icon-button: {
        width: 16px;
        height: 16px;
      };
    }
```

I would expect `iron-icon` will change its size as well.
But it just overflows the container.

**Comment by Inrego** [comment]
Look in the demo how to change the size of the icon. There's an example. I'll quote below:

    <style is="custom-style">
      paper-icon-button.huge {
        margin-left: 0px;
        width: 100px;
        --paper-icon-button-ink-color: var(--paper-indigo-500);
      }

      paper-icon-button.huge::shadow #icon {
        width: 100px;
        height: 100px;
      }

      paper-icon-button.huge #icon {
        width: 100px;
        height: 100px;
      }
    </style>

      <div>
        <h4>Size</h4>
        <div class="horizontal-section">
          <paper-icon-button icon="favorite" alt="heart" class="huge"></paper-icon-button>
          <br><br><br>
          <paper-icon-button icon="polymer" alt="polymer" class="huge"></paper-icon-button>
        </div>
      </div>

**Comment by bendavis78** [comment]
FYI, `::shadow` is being deprecated. There should be way to allow changing icon size without having to pierce shadowdowm.

**Comment by notwaldorf** [comment]
Just changing the size of the paper-icon-button is enough (no ::shadow
needed):
```
paper-icon-button.huge {
  width: 50px;
  height: 50px;
}
```
You can see this at work in the demo:
https://elements.polymer-project.org/elements/paper-icon-button?view=demo:demo/index.html&active=paper-icon-button

**Comment by andrewebdev** [comment]
There is another related issue here that I just ran into; So I hope you don't mind if I post it here.
You cannot resize the icon inside the button anymore.

I have a very large paper-icon-button (78x78), but I need the iron-icon inside to be 40x40.

Using...

    .btnClass {
        --iron-icon-width: 40px;
        --iron-icon-height: 40px;
    }

... used to work fine, until I ran a bower update. Now all icons inside paper-icon-button seems to ignore my custom sizing.

**Comment by notwaldorf** [comment]
You no longer need to use custom properties to resize the icon -- just resizing the button is enough to resize your icon (your example does both, which is why you probably can't reproduce anymore)

**Comment by andrewebdev** [comment]
@notwaldorf a bit of confusion there. The use case I'm currently needing, is that I need to resize the button to one size, but need to resize the icon inside the button to another. I very specifically need the icon to be about half the size of the actual button. Quick and dirty example: https://jsbin.com/quzegaguwi/edit?html,output

Anyway, there must be something I'm doing wrong on my end, I just found it strange that it suddenly stopped working after the update. There could be something else on a higher level that changed, and trickles down to  my component

**Comment by andrewebdev** [comment]
Actually I've now tested a bit more and it does seem to be this commit here 3c0baf946c17466a5b5ab0020cda6f4751a1dddb which, in my opinion, regressed the theming ability somewhat.

Specifically these lines here: https://github.com/PolymerElements/paper-icon-button/blob/3c0baf946c17466a5b5ab0020cda6f4751a1dddb/paper-icon-button.html#L96-L99

The icon size if forced to be the size of the button, and this cannot be overridden, other than piercing the shadow dom, which is deprecated anyway.

**Comment by notwaldorf** [comment]
Hmm, I can add a mixin probably to let you customize it, but I think I'd like to understand why you want the icon not to be the same size as the button, before I do that. If you just want padding around the icon, `padding` works. Is that enough?

```css
paper-icon-button.different {
    padding:40px;
    width: 100px;
    height: 100px;
}
```
Which produces this:
<img width="116" alt="screen shot 2015-11-06 at 5 31 19 pm" src="https://cloud.githubusercontent.com/assets/1369170/11002286/28d29f48-84ac-11e5-8d71-b542eb3ab438.png">

**Comment by andrewebdev** [comment]
@notwaldorf oh that may actually solve the problem nicely. Didn't think of that! Will give it a try when I'm back in office.

As for background on why you'd want a icon smaller than the button. The designer specifically designed a component with large button, but wants the icon itself in side the button to be half the size. For this use case I agree with the designer because the icon looks far too "fat" at the same size as the button.

**Comment by notwaldorf** [comment]
Looks like it's been fixed!
