### ISSUE TITLE
[1.0] Ripple effect acting weird when changing to another window

### ISSUE THREAD

**Issue by Iskalla** [PolymerElements/paper-icon-button#25]
If I tap a paper-icon-button and then alt+tab or change the navigator tab, whenever I go back to see the page, the ripple effect is on and static. It fades again only after I click anywhere else on the page. You can test this on the demo page - https://elements.polymer-project.org/elements/paper-icon-button?view=demo:demo/index.html

**Comment by alejost848** [comment]
I think that's the normal behavior of a button since that happens when it's in its selected state. I can be wrong though.

**Comment by blasten** [comment]
@alejost848 is right. This is done for accessibility.
