### ISSUE TITLE
Ripple effect not showing on tablet+ layout

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-icon-button#31]
_From @summers173 on August 6, 2015 16:54_

You can reproduce this in the start page of polymer-starter-kit-light-1.0.3

The ripple effect on any paper-icon-button is not showing well, or disappears pretty quickly if the layout of the page is in "bigger mode", it only works well i the layout is small (phones), if you expand the browser window thus changing the layout to a bigger mode the ripple effect don't show well.

It´s is strange but actually in Internet Explorer behaves ok.

Regards

_Copied from original issue: Polymer/polymer#2217_

**Comment by cdata** [comment]
@summers173 can you please provide a reduced test case and re-open this issue? Thanks!

Please refer to our [contributing guidelines](https://github.com/PolymerElements/paper-icon-button/blob/master/CONTRIBUTING.md) for more details.
