### ISSUE TITLE
Doesn't work with dynamic value

### ISSUE THREAD

**Issue by ozasadnyy** [PolymerElements/paper-icon-button#34]
Hello. Thanks for the amazing element, I like it!
But I have an issue, I can't bind dynamic value into `<paper-icon-button></paper-icon-button>`
Here is my code:
```
<template is="dom-repeat" items="[[person.socials]]" as="social">
  <a href="[[social.link]]" target="_blank">
    <paper-icon-button icon="[[social.icon]]"></paper-icon-button>
  </a>
</template>
```

JSON for person object:
```
{
    "id": 2,
    "name": "Just Name",
    "socials": [{
        "icon": "app-icons:gplus",
        "link": "https://plus.google.com"
    }, {
        "icon": "app-icons:twitter",
        "link": "https://twitter.com"
    }, {
        "icon": "app-icons:facebook",
        "link": "https://facebook.com"
    }]
}
```

`app-icons` - it's my custom collection and works without binding,

**Comment by notwaldorf** [comment]
Is this still reproducible? Please re-open with a reproducible jsbin (see https://github.com/PolymerElements/paper-icon-button/blob/master/CONTRIBUTING.md for an example to get your started)
