### ISSUE TITLE
paper-menu-button Bug on tap

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-icon-button#35]
_From @summers173 on August 17, 2015 18:7_

Sometimes (not always) when in the documentation example

```html
<paper-menu-button>
  <paper-icon-button icon="menu" class="dropdown-trigger"></paper-icon-button>
  <paper-menu class="dropdown-content">
    <paper-item>Share</paper-item>
    <paper-item>Settings</paper-item>
    <paper-item>Help</paper-item>
  </paper-menu>
</paper-menu-button>
```

when you tap on paper-icon-button (mobile and desktop) the ink expands but the menu does not open, you have to click right in the middle in order to the event propagate, and sometimes this don't even work.

Thanks in advanced

_Copied from original issue: Polymer/polymer#2289_

**Comment by kungufli** [comment]
+1 same issue here.

**Comment by azakus** [comment]
Can you point me to the exact URL you're talking about? I can't reproduce this with the given example.

**Comment by azakus** [comment]
I also can't reproduce this behavior in the paper-menu-button demo at https://elements.polymer-project.org/bower_components/paper-menu-button/demo/index.html.

**Comment by kungufli** [comment]
In the end I discovered that the `paper-menu-button` have three (3!) different behaviors depending on when you tap the on the screen. (All the records were made from the demo page https://elements.polymer-project.org/bower_components/paper-menu-button/demo/index.html with Chrome 45).

Tap exactly on the `paper-icon-button` (the menu is opened correctly): 
![paper-menu-button](https://cloud.githubusercontent.com/assets/12832388/9628112/09723940-5169-11e5-81bc-7c67d6f97b7b.gif)
Tap slightly out (but not so much) of the `paper-icon-button`  (the menu is opened and self-closed):
![paper-menu-button2](https://cloud.githubusercontent.com/assets/12832388/9628204/9e63d27a-5169-11e5-9093-19dae9210b09.gif)
Tap near the edge of the element (the menu is not opened at all):
![paper-menu-button3](https://cloud.githubusercontent.com/assets/12832388/9628216/ad333304-5169-11e5-8380-f32ad0827d06.gif)

**Comment by summers173** [comment]
@kungufli, great way ti point the issue. The button don't behave as supposed to, I found another issue on the paper-menu-button, the scroll on items not always work if the paper-menu-button is render inside a paper-dialog for example.

All the elements works as expected on the demo page, but this are not real scenarios,

Regards

**Comment by azakus** [comment]
Thanks for the image repros, those are very helpful.
I still can't get this to repro on desktop, but it was very easy to repro with touch.
I'll take a look.

**Comment by kungufli** [comment]
Now it works better, but there is still a minor incongruence: in the case where you tap near the edge of the element the menu is not opened at all but you can see the ripple effect, so you are telling the user that he hit the button, but the menu is not opening.
