### ISSUE TITLE
Ripple gets cropped when not given an explicit height

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-icon-button#38]
![ripple](https://cloud.githubusercontent.com/assets/348551/9584725/b11f1300-4fc7-11e5-983f-25ead88c12f1.png)

The ripple on paper-icon-button can get all funky with flexbox, and in a number of other contexts:

http://jsbin.com/yihezozaze/1/edit?html,console,output

**Comment by ronnyroeller** [comment]
+1

**Comment by notwaldorf** [comment]
I think this is working as intended. If you remove the `flex`, it behaves properly: http://jsbin.com/rifafe/edit?html,console,output. The `flex` should probably go on a container of the button, not the button itself (because you don't want to change the size of the button itself)
