### ISSUE TITLE
Should have CSS custom property way to increase size of the icon

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-icon-button#45]

**Comment by notwaldorf** [comment]
As of the latest release, the icon is 100% of the size of the button, so increasing it is just a matter of increasing the button size (like we do in the demo):
``` 
paper-icon-button.huge {
  width: 200px; height: 200px
}
```

Is there a reason why we want a custom property in particular?

**Comment by frankiefu** [comment]
Then we should have a default width/height set on the `paper-icon-button`.  Right now if I take out the width set in the demo, I get a huge `paper-icon-button`.
<img width="1044" alt="screen shot 2015-09-24 at 3 35 38 pm" src="https://cloud.githubusercontent.com/assets/116360/10088821/7eb4f7a4-62d2-11e5-86c8-e4e53ac25f29.png">

**Comment by blasten** [comment]
+1

**Comment by notwaldorf** [comment]
Ah got it. I'll take a look!
