### ISSUE TITLE
paper-icon-button goes into pressed state and does not fire "on-tap" event on touch devices

### ISSUE THREAD

**Issue by anishcodes** [PolymerElements/paper-icon-button#47]
If you tap on paper-icon-button on its sides (i.e. not exactly in the centre), it goes into pressed state and "on-tap" event is not fired. This is easily reproducible on chrome browser (My version is 45.0.2454.94) on android devices.

![screenshot_2015-09-30-21-47-50](https://cloud.githubusercontent.com/assets/11910941/10199491/8e869c96-67be-11e5-8e5e-0fe3bd3d45a8.png)

**Comment by cdata** [comment]
Hi. Unfortunately, this is a side-effect of fuzzy target detection picking different targets for touch and click events. Please refer to this bug to track progress on the problem: https://github.com/Polymer/polymer/issues/1670
