### ISSUE TITLE
Icon button shouldn't activate on unhandled context-click

### ISSUE THREAD

**Issue by dmazzoni-google** [PolymerElements/paper-icon-button#5]
Right-clicking on an icon button shouldn't show its activation animation. Maybe if it specifically has a long-press handler, it could - but not if it just shows the default browser context menu.

**Comment by notwaldorf** [comment]
(@cdata: there may already be a bug open for this already. looking)

**Comment by notwaldorf** [comment]
Clising as a duplicate of https://github.com/PolymerElements/paper-radio-button/issues/33
(they have the same root case)
