### ISSUE TITLE
Missing ripple in version 1.0.4

### ISSUE THREAD

**Issue by DiJi1001** [PolymerElements/paper-icon-button#53]
I can't see ripple effect in version 1.0.4.
It seems that some code ```<paper-ripple id="ink" class="circle" center></paper-ripple>``` doesn't present in DOM module

**Comment by notwaldorf** [comment]
Did you update `paper-icon-button` without updating any of its dependencies? There were changes downstream that went along with this release (paper-ripple is now created on demand). I think that if you do `bower install` inside of your element, everything should be up to date again :)

(please re-open if updating the dependencies didn't fix this)
