### ISSUE TITLE
on-tap responds only to the first click

### ISSUE THREAD

**Issue by masaoliou** [PolymerElements/paper-icon-button#54]
```html
<paper-icon-button icon="icons:check" title="Confirm" on-tap="IconTapped"></paper-icon-button>
<paper-icon-button icon="icons:help" title="Get Help" on-tap="IconTapped"></paper-icon-button>
```

The following javascript logs `<paper-icon-button>` in response to the first mouse click but it logs `<paper-ripple>` in response to the second and succeeding clicks. As a result, `ev.target.icon` in `IconTapped` becomes `undefined`.
```javascript
IconTapped:function(ev){
	console.log(ev.target);
	switch(ev.target.icon){
		case "icons:check": //Do real job here.
			break;
		case "icons:help": //Do real job here.
			break;
	}
}
```

**Comment by notwaldorf** [comment]
If you do a `bower install` to update your dependencies, you should get the latest version of `paper-ripple` which fixes this.
