### ISSUE TITLE
Customize style on hover

### ISSUE THREAD

**Issue by maxiplay** [PolymerElements/paper-icon-button#55]
In the example demo. We can change the style on hover with

       paper-icon-button.blue:hover {
        background: var(--paper-light-blue-50);
        border-radius: 50%;
      }

But how to customize with cross scope styling in order to centralize the same behavior ?

My solution 

https://github.com/maxiplay/paper-icon-button

**Comment by cdata** [comment]
Hi, could you re-open this issue with a more specific design proposal for the feature?

For more details and suggestions, please refer to our [contribution guidelines](../blob/master/CONTRIBUTING.md)!
