### ISSUE TITLE
Polymer.PaperRadioButtonBehavior doesn't exist

### ISSUE THREAD

**Issue by jahglow** [PolymerElements/paper-icon-button#75]
this behavior doesn't exist in Paper-behaviors and paper-icon-button pointing to it

**Comment by MeTaNoV** [comment]
Solved here: https://github.com/PolymerElements/paper-icon-button/pull/62

**Comment by notwaldorf** [comment]
Is this happening in the latest release? I don't see a `PaperRadioButtonBehavior` import anywhere. Please update your version of `paper-icon-button` and check if it's still happening.

**Comment by jahglow** [comment]
It is happening in the latest release, when I use bower update and
inbowre.json it's ^#1.0.3 so it fetchea the latest. Besides it adds another
paper-ripple so there are two now : one vefore ironicon and one after

пн, 21 марта 2016, 20:46 Monica Dinculescu <notifications@github.com>:
