### ISSUE TITLE
Feature request: Allow configurable size

### ISSUE THREAD

**Issue by miztroh** [PolymerElements/paper-icon-button#76]
Expose ``--iron-icon-width`` and ``--iron-icon-height`` from ``iron-icon``.

https://elements.polymer-project.org/elements/iron-icon

I've had many situations that required a larger icon than ``paper-icon-button`` provides.  I find myself faking it with a ``paper-button`` and an ``iron-icon``.

**Comment by MeTaNoV** [comment]
you can do it already:
```
<style is="custom-style">
  paper-icon-button.giant {
    width: 100px;
    height: 100px;
  }
</style>
<paper-icon-button icon="alarm-on" title="wake up" class="giant"></paper-icon-button>
```
See the demo page: https://elements.polymer-project.org/elements/paper-icon-button?view=demo:demo/index.html&active=paper-icon-button

**Comment by notwaldorf** [comment]
Yup, as @MeTaNoV mentioned, this is already possible just by changing the `paper-icon-button`'s size. Closing.

**Comment by miztroh** [comment]
@MeTaNoV, @notwaldorf: Ah, awesome.  Thanks!
