### ISSUE TITLE
The alternative button demo doesn't look good

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-icon-button#77]
### Description

The alternative button demo doesn't look good.

### Expected outcome

![screen shot 2016-04-04 at 18 18 16](https://cloud.githubusercontent.com/assets/1007051/14254792/a0083752-fa91-11e5-9684-afa2653e93b9.png)

### Actual outcome

![screen shot 2016-04-04 at 18 15 21](https://cloud.githubusercontent.com/assets/1007051/14254806/a945c83e-fa91-11e5-8473-2f8e3ff78d23.png)

### Live Demo

https://elements.polymer-project.org/elements/paper-menu-button?view=demo:demo/index.html&active=paper-menu-button

**Comment by notwaldorf** [comment]
Closing, as I can't repro this anymore on Chrome/FF/Safari:
<img width="285" alt="screen shot 2016-05-31 at 11 50 11 am" src="https://cloud.githubusercontent.com/assets/1369170/15686587/e394b4d0-2725-11e6-8fc3-2e1116c4b1bc.png">

Please re-open if it's still reproducible.

**Comment by abdonrd** [comment]
Now looks well. Magic! 😮
