### ISSUE TITLE
Why does a disabled icon-button have pointer-events: none?

### ISSUE THREAD

**Issue by dmazzoni-google** [PolymerElements/paper-icon-button#8]
I believe that prevents hovering over it to get a tooltip. I noticed when I tried to use the inspector element picker to observe it and couldn't reach it that way.

pointer-events: none should probably only be used for things that are transparent overlays or purely presentational, not just for real controls that are temporarily in a disabled state.

**Comment by notwaldorf** [comment]
`pointer-events:none` is a inexpensive way to make the icon not clickable, which is what `disabled` should do. Please re-open if this causes a practical problem for accessibility.
