### ISSUE TITLE
Click error in the paper-icon-button

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-icon-button#84]
### Description

Click error in the paper-icon-button.
Original issue: https://github.com/Polymer/shop/issues/33
### Expected outcome

Normal click. :)
### Actual outcome

I record a GIF to show the problem:

![shop-paper-icon-button](https://cloud.githubusercontent.com/assets/1007051/15559345/9ddcb214-22e1-11e6-9f76-f7fa0d32b3d1.gif)
### Live Demo

https://shop.polymer-project.org

**Comment by keanulee** [comment]
The root cause is described here: https://plus.google.com/+RickByers/posts/TzmJkM3HdCt. The coordinates for `click` are adjusted (so the focus ripple appears), but `tap` isn't fired because coordinates for `touchstart` are not adjusted.

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
