### ISSUE TITLE
Add Style Examples To Doc

### ISSUE THREAD

**Issue by phidias51** [PolymerElements/paper-icon-button#87]
Please add more styling examples to the doc.  Specifically examples that show how to set the height and width.  **iron-icon** uses **--iron-icon-height**, and **--iron-icon-width** so the expectation is that **--paper-icon-button-height** and **--paper-icon-width** should do the trick here.  Since that's not the case, some doc would help.

**Comment by hemantjadon** [comment]
I have added the required docs. Please Review

**Comment by notwaldorf** [comment]
This was already fixed
