### ISSUE TITLE
Better default ink color

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/paper-icon-button#97]
Could you set default ink color to `currentColor`? 

``` css
color: var(--paper-icon-button-ink-color, --primary-text-color);
```

TO

``` css
color: var(--paper-icon-button-ink-color, currentColor);
```

https://github.com/PolymerElements/paper-icon-button/blob/master/paper-icon-button.html#L101
https://github.com/PolymerElements/paper-icon-button/blob/master/paper-icon-button-light.html#L49

**Comment by notwaldorf** [comment]
I don't think this is right, as it would then be inconsistent with all the other paper-elements (which all have the same ink color, as per material design specs). I would recommend just changing  `--paper-icon-button-ink-color` instead
